import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import {
  SignInButton,
  SignOutButton,
  UserButton,
  useUser,
} from "@clerk/nextjs";

import { ThemeToggle } from "@/components/theme-toggle";
import { Skeleton } from "@/components/ui/skeleton";

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* dark:from-[#2e026d] dark:to-[#15162c] */}
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-100 to-slate-300 dark:from-slate-800 dark:to-slate-950">
        <ThemeToggle />
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && (
            <div>
              <UserButton /> <SignOutButton />
            </div>
          )}
        </div>
        {/* <Skeleton className="h-12 w-64" /> */}
        {!isLoading && (
          <div>
            {data?.map((post) => (
              <div key={post.id}>{post.content}</div>
            ))}
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
